# Generated by Django 3.2.15 on 2022-08-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('start_date', models.DateField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('N', 'None'), ('D', 'Daily'), ('W', 'Weekly'), ('Y', 'Yearly'), ('M', 'Monthly'), ('MW', 'Monthly on nth weekday'), ('MLW', 'Monthly on last weekday')], default='N', max_length=3)),
                ('end_date', models.DateField(blank=True, help_text='Last day for recurring events. Leave blank for one-time events to use the same as start date', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['start_date', 'time'],
            },
            bases=('pages.basepage',),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventcategory'),
        ),
    ]
