# Generated by Django 3.2.15 on 2022-08-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='color',
            field=models.CharField(choices=[('category-gray', 'Gray'), ('category-blue', 'Blue'), ('category-green', 'Green'), ('category-yellow', 'Yellow'), ('category-orange', 'Orange'), ('category-red', 'Red'), ('category-purple', 'Purple')], default='category-gray', max_length=20),
        ),
    ]
