# Generated by Django 3.2.16 on 2023-01-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='include_rsvp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_all_day',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('number_attending', models.IntegerField(default=1)),
                ('event_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventoccurrence')),
            ],
        ),
    ]
