# Generated by Django 3.2.15 on 2022-08-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
                ('published', models.DateField(blank=True, help_text="Leave blank to use today's date")),
            ],
            options={
                'verbose_name': 'News Item',
                'ordering': ['-published'],
            },
            bases=('pages.basepage',),
        ),
    ]
