# Generated by Django 3.2.15 on 2022-08-31 13:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, help_text='Leave blank to auto generate', max_length=1024)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto generate')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basepage')),
            ],
            bases=('pages.basepage',),
        ),
    ]
