# Generated by Django 3.2.15 on 2022-09-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='status',
            field=models.IntegerField(choices=[('0', 'Draft'), ('1', 'Published')], default='0'),
        ),
    ]
