# Generated by Django 3.2.16 on 2023-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
