# Generated by Django 3.2.15 on 2022-08-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('cta_text', models.CharField(max_length=15)),
                ('cta_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Announcement',
            },
        ),
    ]
